- .browserslistrc
- .gitignore
- README.md
- package-lock.json
- package.json
- postcss.config.js
- src/assets/mdi.ts
- src/components/Navigation/List.vue
- src/components/Navigation/ListItem.vue
- src/components/Navigation/LogoAndTitle.vue
- src/components/Navigation/Navigation.vue
- src/components/UI/Icon.vue
- src/index.scss
- src/router/index.ts
> Navigationの軽い実装

- src/components/Navigation/ListItem.vue
- src/components/Navigation/Navigation.vue
- src/index.scss
- src/styles/common.scss
> feat style

- src/components/ItemDetail/Controls.vue
> selectorの書き方のfix

- src/components/Navigation/Navigation.vue
- src/components/Navigation/Search.vue
- src/lib/params.ts
- src/pages/Items.vue
- src/pages/use/syncParam.ts
> サイドバーでの検索の実装

- src/App.vue
- src/components/ItemDetail/Controls.vue
- src/components/ItemDetail/use/borrow.ts
- src/components/ItemDetail/use/return.ts
- src/pages/DashBoard.vue
- src/store/index.ts
- src/use/me.ts
割と簡単に使えそうな感じにできたと思う
close #145
> meをstoreに格納してそれを利用するように close #145

- src/components/ItemDetail/BorrowDialog.vue
- src/components/ItemDetail/Controls.vue
- src/components/ItemDetail/OtherControls.vue
- src/components/ItemDetail/ReturnDialog.vue
- src/components/UI/Icon.vue
- src/components/UI/IconButton.vue
- src/components/UI/NormalIconButton.vue
- src/components/UI/WideIconButton.vue
> Other controls

- src/components/BorrowedItem.vue
- src/components/ItemWide/ItemWide.vue
- src/pages/DashBoard.vue
ユーザーページとの共通コンポーネントのItemWide
同時にダッシュボードすこしデザイン変えた
refs #131
> ItemWideとダッシュボードの変更

- src/components/ItemDetail/AddOwnerDialog.vue
- src/components/ItemDetail/EditDialog.vue
- src/components/ItemDetail/OtherControls.vue
- src/components/ItemDetail/OwnerSelector.vue
- src/components/ItemDetail/use/addOwner.ts
- src/components/ItemDetail/use/deleteItem.ts
- src/components/ItemDetail/use/editItem.ts
- src/components/ItemDetail/use/otherControl.ts
- src/components/ItemDetail/use/owners.ts
> その他のコントロールボタンのロジック実装

- src/components/Navigation/Navigation.vue
- src/components/Navigation/Search.vue
- src/components/UI/SearchInput.vue
- src/pages/Items.vue
> 検索コンポーネント close #157

- package-lock.json
- package.json
- src/components/Item/Item.vue
- src/components/ItemDetail/OtherControls.vue
- src/components/ItemDetail/use/addOwner.ts
- src/components/RegisterForm/RegisterForm.vue
- src/components/RegisterForm/RegisterFormDescription.vue
- src/components/RegisterForm/RegisterFormImage.vue
- src/components/RegisterForm/RegisterFormImageButton.vue
- src/components/RegisterForm/RegisterFormOwner.vue
- src/components/RegisterForm/UrlInputDialog.vue
- src/components/RegisterForm/use/completeFromCode.ts
- src/components/RegisterForm/use/formState.ts
- src/components/RegisterForm/use/imageUpload.ts
- src/components/UI/InputCheckbox.vue
- src/components/UI/InputNumber.vue
- src/components/UI/InputText.vue
- src/components/UI/MiniPopup.vue
- src/components/UI/SearchInput.vue
- src/components/UI/Selector.vue
- src/components/UI/WithFocusUnderline.vue
- src/styles/animation.scss
- src/styles/common.scss
- src/types/ungap-promise-any.d.ts
> 物品登録ページの改善

- src/components/ItemDetail/AddOwnerDialog.vue
- src/components/ItemDetail/BorrowDialog.vue
- src/components/ItemDetail/EditDialog.vue
- src/components/ItemDetail/OwnerSelector.vue
- src/components/ItemDetail/ReturnDialog.vue
- src/components/ItemDetail/use/borrow.ts
- src/components/RegisterForm/RegisterFormDescription.vue
- src/components/RegisterForm/RegisterFormOwner.vue
- src/components/RegisterForm/UrlInputDialog.vue
- src/components/UI/DialogTemplate.vue
- src/components/UI/InputDate.vue
- src/components/UI/InputNumber.vue
- src/components/UI/InputText.vue
- src/components/UI/Selector.vue
> 各種モーダルのスタイル close #180

- src/components/Item/Item.vue
- src/components/ItemDetail/LikeButton.vue
- src/styles/common.scss
ホントにハートにしただけ
レスポンスに誰がいいねしたか入ってなくていいねの数しか入ってなかった
> 一覧画面でのいいねの表示をハートにする 

- src/components/ItemDetail/use/otherControl.ts
> 備品は所有者追加ボタンを無効化 fix #488

- src/components/ItemDetail/use/deleteItem.ts
> 削除時の確認メッセージの変更 fix #487

- src/components/ItemDetail/BorrowDialog.vue
- src/components/ItemDetail/ReturnDialog.vue
- src/components/ItemDetail/use/borrow.ts
- src/components/UI/InputNumber.vue
> 個数が必ず1のとき個数選択を非表示ではなくdisabledに変更 close #146

- package-lock.json
- package.json
- src/types/rollup-plugin-brotli.d.ts
- vite.config.ts
> Brotli compression

- src/components/RegisterForm/RegisterFormImage.vue
- src/components/RegisterForm/use/imageUpload.ts
> 画像を確定させたらinputを作り直すように

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/staging.yml
ファイル名じゃなくてファイルパスが表示されてびみょいになった
> add workflow name

- vite.config.ts
ローカルで環境を立てた時にDNS周りでエラーが出ていたやつの修正です
//q.trap.jp/messages/ec5b348e-cade-47ed-9551-770a3daef864
> DNS lookup時にIPv4を優先

- src/components/ItemDetail/composables/useOwners.ts
このissueへの対応
https://github.com/traPtitech/booQ/issues/508
手元で`npm run dev`で見ようとするとbad requestなるので動作確認は取れてません
> 1つも所有していないownerを表示から排除

- src/components/RegisterForm/composables/useCompleteFromCode.ts
API: https://github.com/traPtitech/booQ/pull/542
> NDLから書影を受け取るように修正

- Dockerfile
> ビルドに使うDockerfileのバージョンを更新
